/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */







/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* genCollectivePK(GoString cpkStr, GoInt numPeers, GoUint64 logDegree, GoFloat64 scale);
extern char* aggregateEncrypted(GoString encInputsString, GoInt numPeers, GoUint64 logDegree, GoFloat64 scale, GoInt inputLength);

/* Return type for genTPK */
struct genTPK_return {
	char* r0; /* res */
	char* r1; /* tsk_Cstring */
};
extern struct genTPK_return genTPK(GoUint64 logDegree, GoFloat64 scale);
extern char* decrypt(GoString tsk_string, GoString pcksShareString, GoString encResultStr, GoUint64 logDegree, GoFloat64 scale, GoInt inputLength, GoInt numPeers);
extern char* genShamirShares(GoInt numPeers, GoUint8 robust, GoUint64 logDegree, GoFloat64 scale, GoFloat64 resiliency);

/* Return type for genCollectiveKeyShair_not_robust */
struct genCollectiveKeyShair_not_robust_return {
	char* r0; /* res */
	char* r1; /* shamirShareString */
};
extern struct genCollectiveKeyShair_not_robust_return genCollectiveKeyShair_not_robust(GoInt numPeers, GoUint8 robust, GoUint64 logDegree, GoFloat64 scale, GoFloat64 resiliency);
extern char* encryptMsg(GoSlice inputs, GoString cpkString, GoString shamirShareString, GoUint8 robust, GoUint64 logDegree, GoFloat64 scale);
extern char* genPCKSShare(GoString enc_aggr_model, GoString TPK, GoString shamirShareString, GoUint64 decryptionCoefficient, GoInt inputLength, GoUint8 robust, GoUint64 logDegree, GoFloat64 scale);

#ifdef __cplusplus
}
#endif
